### ISSUE TITLE
Development instructions

### ISSUE THREAD

**Issue by biou** [jpramosi/geckordp#1]
Hi, thanks for this very promising tool!
I would be interested in using it for accessibility testing, by using the features available in the accessibility tab of the devtools.

I followed the instructions on the develop section of your readme.md, but I did not succeed to start 2 parallel instances of firefox on Linux and on MacOS. 

The issue is that the geckordp profile was not yet created. May I send a PR with some update to the documentation to bring some precisions about this step?

**Comment by jpramosi** [comment]
Thanks for your feedback. Yes, you are right. It's missing one important step. Maybe i should include a binary which is able to create the profiles on terminal and add it to the docs later.
But yes you can already send a pull request if you would like, no problem.
If you think the documentation is vaguely explained or can be explained better, you are always welcome to also send a PR.

Furthermore did Geckordp work flawless on MacOs (examples, tests)?
I had no chance to try it beforehand, since the OS is not available for me.

**Comment by jpramosi** [comment]
I reduced the wall of text in the [readme](https://github.com/reapler/geckordp/tree/master/dev) and implemented new [actors](https://github.com/reapler/geckordp/commit/d3b46b81b82b3e3618b4b92cd1091b322602e722).
If there's something missing, please let me know.

**Comment by biou** [comment]
Sorry I haven't had the time to contribute. The new readme is really clearer, thanks for that! 
On top of that you have integrated accessibility actors, many thanks!
