### ISSUE TITLE
How to hide robot icon and tips?

### ISSUE THREAD

**Issue by hkfsc** [jpramosi/geckordp#2]
![x](https://user-images.githubusercontent.com/103763990/168423356-7a9338f7-bc05-415a-ac47-679bf9b16f6d.png)

Tried set `useAutomationExtension=False`, but it still not work, thanks!
```
profile = pm.get_profile_by_name(profile_name)
profile.set_config("useAutomationExtension", False)
profile.set_config("dom.webdriver.enabled", False)
profile.set_required_configs()
```

**Comment by jpramosi** [comment]
To the best of my knowledge this cannot be hidden, since it is hardcoded in Firefox.
If I recall it correctly the developers made these changes to avoid malware to silently intercepting Firefox instances without the knowledge of the user.
At least the robot marking on the address bar, cannot be detected on web pages with anti-bot scripts (if you worry about this problem).

**Comment by hkfsc** [comment]
> To the best of my knowledge this cannot be hidden, since it is hardcoded in Firefox. If I recall it correctly the developers made these changes to avoid malware to silently intercepting Firefox instances without the knowledge of the user. At least the robot marking on the address bar, cannot be detected on web pages with anti-bot scripts (if you worry about this problem).

Aha, its just annoying, and if it can do the work well without been detected, I should have to accept that there are no ways to hide issue, thanks for your reply!
